SET @start_date = DATE_SUB(CURDATE(), INTERVAL 30 DAY);
SET @vol = 85000;

-- Stock 1 (TFLOW)
INSERT INTO price_history (date, stock_id, open_price, high_price, low_price, close_price, volume)
SELECT DATE_ADD(@start_date, INTERVAL n DAY), 1, 
       ROUND(200 + n * 1.5, 2), ROUND(205 + n * 1.5, 2), ROUND(195 + n * 1.5, 2), ROUND(200 + n * 1.5 + RAND()*3, 2), @vol + RAND()*10000
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30) n;
-- Update last day to exact current price
UPDATE price_history SET close_price = 248.12 WHERE stock_id = 1 AND date = CURDATE();

-- Stock 2 (HSYNC)
INSERT INTO price_history (date, stock_id, open_price, high_price, low_price, close_price, volume)
SELECT DATE_ADD(@start_date, INTERVAL n DAY), 2, 
       ROUND(65 + n * 0.5, 2), ROUND(68 + n * 0.5, 2), ROUND(62 + n * 0.5, 2), ROUND(65 + n * 0.5 + RAND()*2, 2), @vol + RAND()*5000
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30) n;
UPDATE price_history SET close_price = 80.34 WHERE stock_id = 2 AND date = CURDATE();

-- Stock 3 (FMTRIC)
INSERT INTO price_history (date, stock_id, open_price, high_price, low_price, close_price, volume)
SELECT DATE_ADD(@start_date, INTERVAL n DAY), 3, 
       ROUND(150 + n * 0.9, 2), ROUND(155 + n * 0.9, 2), ROUND(148 + n * 0.9, 2), ROUND(150 + n * 0.9 + RAND()*3, 2), @vol + RAND()*6000
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30) n;
UPDATE price_history SET close_price = 178.30 WHERE stock_id = 3 AND date = CURDATE();

-- Stock 4 (EDUHB)
INSERT INTO price_history (date, stock_id, open_price, high_price, low_price, close_price, volume)
SELECT DATE_ADD(@start_date, INTERVAL n DAY), 4, 
       ROUND(130 + n * 0.8, 2), ROUND(135 + n * 0.8, 2), ROUND(125 + n * 0.8, 2), ROUND(130 + n * 0.8 + RAND()*2, 2), @vol + RAND()*8000
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30) n;
UPDATE price_history SET close_price = 156.00 WHERE stock_id = 4 AND date = CURDATE();

-- Stock 5 (GRNEV)
INSERT INTO price_history (date, stock_id, open_price, high_price, low_price, close_price, volume)
SELECT DATE_ADD(@start_date, INTERVAL n DAY), 5, 
       ROUND(270 + n * 1.4, 2), ROUND(280 + n * 1.4, 2), ROUND(260 + n * 1.4, 2), ROUND(270 + n * 1.4 + RAND()*4, 2), @vol + RAND()*15000
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30) n;
UPDATE price_history SET close_price = 313.50 WHERE stock_id = 5 AND date = CURDATE();

-- Stock 6 (AGRIX)
INSERT INTO price_history (date, stock_id, open_price, high_price, low_price, close_price, volume)
SELECT DATE_ADD(@start_date, INTERVAL n DAY), 6, 
       ROUND(50 + n * 0.5, 2), ROUND(53 + n * 0.5, 2), ROUND(48 + n * 0.5, 2), ROUND(50 + n * 0.5 + RAND()*1.5, 2), @vol + RAND()*2000
FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30) n;
UPDATE price_history SET close_price = 67.20 WHERE stock_id = 6 AND date = CURDATE();
